import eUkraine from "@/assets/fonts";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    viewport: "width=device-with, initial-scale=1"
};

export default function ServerLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={eUkraine.variable}>{children}</body>
        </html>
    );
}
